---
title: "Final_Seurat_Countland_comparison_withSilhouetteScore"
output: rmarkdown::github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


# Function to perform clustering analysis with adjustable parameters
run_clustering_analysis <- function(gold_data, 
                                   dims = 1:10, 
                                   resolution = 0.15, 
                                   n_clusters = 7, 
                                   n_components = 5) {
  
  # Load required libraries
  library(countland)
  library(dplyr)
  library(Seurat)
  library(networkD3)
  library(patchwork)
  library(Matrix)
  library(ggplot2)
  library(Azimuth)
  library(gridExtra)
  library(cluster) 
  
  # Set theme
  theme_set(theme_classic())
  
  # Create Seurat object
  gold <- CreateSeuratObject(counts = gold_data, project = "gold3k", min.cells = 3, min.features = 200)
  
  # Initialize countland object
  C <- countland(gold_data, remove_empty = TRUE)
  C@names_genes <- gsub("_", "-", C@names_genes) # set names equal to Seurat
  
  # Filter cells in countland
  C <- ScoreCells(C)
  cell_filt <- C@cell_scores[C@cell_scores$n_features >= 200,]$names
  C <- SubsetCells(C, which(C@names_cells %in% cell_filt), remove_empty = FALSE)
  
  # Score and filter genes in countland
  C <- ScoreGenes(C, subsample = FALSE)
  gene_filt <- C@gene_scores[C@gene_scores$n_cells >= 3,]$names
  C <- SubsetGenes(C, which(C@names_genes %in% gene_filt), remove_empty = FALSE)
  
  # Score cells for mitochondrial genes
  gene_string <- "^MT-"
  C <- ScoreCells(C, gene_string)
  
  # Find variable features in Seurat
  gold <- FindVariableFeatures(gold, selection.method = "vst", nfeatures = 2000)
  
  # Subsample and score genes in countland
  C <- Subsample(C, cell_counts = 300)
  C <- ScoreGenes(C, subsample = TRUE)
  
  # Subset genes in countland to match Seurat variable features
  C <- SubsetGenes(C, which(C@names_genes %in% rownames(gold)[gold@assays$RNA@meta.data$vf_vst_counts_variable]))
  
  # Seurat Clustering Workflow
  gold <- NormalizeData(gold)
  all.genes <- rownames(gold)
  gold <- ScaleData(gold, features = all.genes)
  gold <- RunPCA(gold, features = VariableFeatures(object = gold), verbose = FALSE)
  gold <- FindNeighbors(gold, dims = dims)
  gold <- FindClusters(gold, resolution = resolution)
  gold <- RunUMAP(gold, dims = dims)
  
  # Countland Clustering Workflow
  C <- Dot(C)
  C <- Embed(C)
  C <- Cluster(C, n_clusters = n_clusters, n_components = n_components)

  
  # **Silhouette Score Calculation (Encapsulated Inside the Function)**
  calculate_silhouette <- function(coords, clusters) {
    sil_scores <- cluster::silhouette(clusters, dist(coords))
    mean_sil <- mean(sil_scores[,3])  # Extract mean silhouette score
    return(mean_sil)
  }
  
  # Compute Silhouette Scores for Seurat object and Countland object
  seurat_silhouette <- calculate_silhouette(gold@reductions$umap@cell.embeddings, as.numeric(gold@meta.data$seurat_clusters))
  
  countland_silhouette <- calculate_silhouette(C@embedding[, c(2,3)], as.numeric(C@cluster_labels))
  
    
  # Run Azimuth for cell type annotation
  gold <- RunAzimuth(gold, reference = "pbmcref")
  
  # Create broad cell type annotations
  predicted.celltype.l1 <- c("CD4 T", "CD8 T", "other T", "B", "Mono", "NK", "other", "DC")
  broad.annotation <- c("T", "T", "T", "B", "Mono", "NK", "other", "DC")
  map <- setNames(broad.annotation, predicted.celltype.l1)
  
  # Add broad annotations to Seurat metadata
  gold@meta.data[["broad.annotation"]] <- map[gold@meta.data |> pull(predicted.celltype.l1)]
  
  # Transfer cell type annotations from Seurat to countland
  n <- rownames(gold@meta.data)
  v1 <- gold@meta.data |> pull(broad.annotation)
  v2 <- gold@meta.data |> pull(predicted.celltype.l1)
  
  map1 <- setNames(v1, n)
  map2 <- setNames(v2, n)
  
  C@cell_scores[["broad.annotation"]] <- map1[C@cell_scores[["names"]]]
  C@cell_scores[["predicted.celltype.l1"]] <- map2[C@cell_scores[["names"]]]
  
  # Create data for visualization
  cl_s <- paste0(gold@meta.data$seurat_clusters)
  cl_r <- paste0(gold@meta.data$orig.ident)
  cl_c <- paste0(as.character(C@cluster_labels))
  cl_b <- paste0(as.character(C@cell_scores[["broad.annotation"]]))
  cl_f <- (as.character(C@cell_scores[["predicted.celltype.l1"]]))
  values <- unique(c(cl_s, cl_c, cl_r, cl_b))
  color <- viridis::turbo(n = length(values))
  names(color) <- values
  
  # Visualize results using Seurat UMAP
  u1 <- gold@reductions$umap@cell.embeddings[,1]
  u2 <- gold@reductions$umap@cell.embeddings[,2]
  gdf_seurat <- data.frame(
    "component1" = u1, 
    "component2" = u2, 
    "real_label" = cl_r, 
    "seurat_clusters" = cl_s, 
    "countland_clusters" = cl_c, 
    "countland_annotation" = cl_b, 
    "predicted.celltype.l1" = cl_f
  )
  
  # Visualize results using countland embedding
  u1_spectral <- C@embedding[,2]
  u2_spectral <- C@embedding[,3]
  gdf_spectral <- data.frame(
    "component1" = u1_spectral, 
    "component2" = u2_spectral, 
    "real_label" = cl_r, 
    "seurat_clusters" = cl_s, 
    "countland_clusters" = cl_c, 
    "countland_annotation" = cl_b
  )
  
 # first we calculate the correspondence between clusters
get_cluster_comb_df <- function(cl1,cl2){
  return(data.frame('source'=cl1,'target'=cl2) %>% group_by(source,target) %>% count())
}
r1 <- get_cluster_comb_df(cl_r,cl_c)
r2 <- get_cluster_comb_df(cl_s,cl_r)
r <- bind_rows(r1,r2)

# A connection data frame is a list of flows with intensity for each flow
links <- data.frame(
  source=r$source, 
  target=r$target, 
  value=r$n
  )
 
# From these flows we need to create a node data frame: it lists every entities involved in the flow
nodes <- data.frame(
  name=c(as.character(links$source), 
  as.character(links$target)) %>% unique()
)

# Here we set up the custom color scheme
my_color <- 'd3.scaleOrdinal() .domain(["seurat_cluster:0", "seurat_cluster:3", "seurat_cluster:2", "seurat_cluster:1", "countland_cluster:2", "countland_cluster:1", "countland_cluster:3", "cell_label:H2228", "cell_label:H1975", "cell_label:HCC827"]) .range(["#30123BFF",  "#4662D7FF",  "#36AAF9FF",  "#1AE4B6FF",  "#72FE5EFF",  "#C7EF34FF",  "#FABA39FF",  "#F66B19FF",  "#CB2A04FF",  "#7A0403FF"])'

# With networkD3, connection must be provided using id, not using real name like in the links dataframe.. So we need to reformat it.
links$IDsource <- match(links$source, nodes$name)-1 
links$IDtarget <- match(links$target, nodes$name)-1
 
# Make the Network
sankey_plot <- sankeyNetwork(Links = links, Nodes = nodes,
              Source = "IDsource", Target = "IDtarget",
              Value = "value", NodeID = "name", 
              sinksRight=TRUE, colourScale = my_color)
  
  # Return all relevant objects and data frames
  results <- list(
    seurat_obj = gold,
    countland_obj = C,
    seurat_umap_data = gdf_seurat,
    countland_embedding_data = gdf_spectral,
    seurat_silhouette = seurat_silhouette,
    countland_silhouette = countland_silhouette,
    sankey_plot = sankey_plot,
    sankey_data = list(
      links = links,
      nodes = nodes
    ),
    parameters = list(
      dims = dims,
      resolution = resolution,
      n_clusters = n_clusters,
      n_components = n_components
    )
  )
  
  return(results)
}



```



```{r}
# Example usage:
# First, load the data
 gold.data <- Seurat::Read10X(data.dir = "/tank2/jpatel/CR_count_results/Pooled_Samples/4plex_subpool1_run1_count/outs/filtered_feature_bc_matrix")

```


```{r}
# Run the analysis with default parameters
# results <- run_clustering_analysis(gold.data)

```



```{r}
# Or run with custom parameters
 results <- run_clustering_analysis(gold.data, 
                                   dims = 1:20, 
                                   resolution = 0.08, 
                                   n_clusters = 6, 
                                   n_components = 3)

```


```{r}
# Access the results
seurat_obj <- results$seurat_obj
countland_obj <- results$countland_obj
umap_data <- results$seurat_umap_data
spectral_data <- results$countland_embedding_data
sankey_plot <- results$sankey_plot
sankey_links <- results$sankey_data$links
sankey_nodes <- results$sankey_data$nodes
```


```{r}
# Visualize the results (Seurat UMAP)
plot_results <- function(results) {
  # Plot Seurat UMAP results
  g1 <- ggplot(results$seurat_umap_data, 
               aes(x = component1, y = component2, color = seurat_clusters)) + 
    geom_point(size = 1) + 
    theme(legend.position = "top") + 
    ggtitle("Seurat clustering")
  
  g2 <- ggplot(results$seurat_umap_data, 
               aes(x = component1, y = component2, color = countland_clusters)) + 
    geom_point(size = 1) + 
    theme(legend.position = "top") + 
    ggtitle("Countland clustering")
  
  g3 <- ggplot(results$seurat_umap_data, 
               aes(x = component1, y = component2, color = predicted.celltype.l1)) + 
    geom_point(size = 1) + 
    theme(legend.position = "top") + 
    ggtitle("Cell type annotations")
  
  seurat_plots <- gridExtra::grid.arrange(g1, g2, g3, ncol = 3)
  
  # Plot Countland spectral embedding results
  g4 <- ggplot(results$countland_embedding_data, 
               aes(x = component1, y = component2, color = seurat_clusters)) + 
    geom_point(size = 1) + 
    theme(legend.position = "top") + 
    ggtitle("Seurat clustering")
  
  g5 <- ggplot(results$countland_embedding_data, 
               aes(x = component1, y = component2, color = countland_clusters)) + 
    geom_point(size = 1) + 
    theme(legend.position = "top") + 
    ggtitle("Countland clustering")
  
  g6 <- ggplot(results$countland_embedding_data, 
               aes(x = component1, y = component2, color = countland_annotation)) + 
    geom_point(size = 1) + 
    theme(legend.position = "top") + 
    ggtitle("Broad annotations")
  
  countland_plots <- gridExtra::grid.arrange(g4, g5, g6, ncol = 3)
  
  return(list(seurat_plots = seurat_plots, countland_plots = countland_plots, sankey_plot = results$sankey_plot))
}

```


```{r fig.height=4,fig.width=15,fig.align="center"}
# Example for plotting:
 plots <- plot_results(results)
```




```{r  sankey-high, fig.height=4,fig.width=4}
#Access and display Sankey plot specifically
plots$sankey_plot
```



```{r Silhouette_Score_Seurat_Clusters}
print(results$seurat_silhouette) 
```


```{r Silhouette_Score_Countland_Clusters}
print(results$countland_silhouette)
```


?silhouette

















































